apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysqldb
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  mycnf: "max_connections = 500"
  router:
    instances: 1
