apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: kamailio-pods
---
# which generate it with following cmd
# k create role kamailio-service-viewer --verb=get --verb=watch \
#   --resource=service --resource-name=kamailio --dry-run=client -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kamailio-service-viewer
  namespace: default
rules:
- apiGroups:
  - ""
  resourceNames:
  - kamailio
  resources:
  - services
  verbs:
  - get
  - watch
--- 

# create this role binding with following cmd
# k create rolebinding kamailio-service-rolebinding --role=kamailio-service-viewer \
#   --serviceaccount=default:kamailio-pods  --dry-run=client -o yaml -n default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: kamailio-service-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kamailio-service-viewer
subjects:
- kind: ServiceAccount
  name: kamailio-pods
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: kamailio
  labels:
    app: kamailio
spec:
  type: LoadBalancer
  selector:
    app: kamailio
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060

---
apiVersion: v1
kind: Service
metadata:
  name: kamailio-headless
  labels:
    app: kamailio
spec:
  type: LoadBalancer
  selector:
    app: kamailio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kamailio-stateful
  labels:
    app: kamailio
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kamailio
  serviceName: "kamailio"
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      serviceAccountName: kamailio-pods
      volumes:
        - name: rtpengine-config
          emptyDir: {}
        - name: kamailio-config
          configMap:
            name: kamailio-config
      initContainers:
        - name: init-rtpengine-config
          image: tutum/dnsutils
          env:
            - name: DB_SVC_NAME
              valueFrom:
                configMapKeyRef:
                  name: kamailio-db-config
                  key: DB_SVC_NAME
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kamailio-db-config
                  key: DATABASE
            - name: RW_USER
              valueFrom:
                secretKeyRef:
                  name: kamailio-db-secret
                  key: RW_USER
            - name: RW_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kamailio-db-secret
                  key: RW_PASSWD
            - name: RO_USER
              valueFrom:
                secretKeyRef:
                  name: kamailio-db-secret
                  key: RO_USER
            - name: RO_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kamailio-db-secret
                  key: RO_USER
            - name: DBURL
              value: "mysql://$(RW_USER):$(RW_PASSWD)@$(DB_SVC_NAME)/$(DATABASE)"
            - name: DBROURL
              value: "mysql://$(RO_USER):$(RO_PASSWD)@$(DB_SVC_NAME):6447/$(DATABASE)"
          command: ["/bin/bash"]
          args:
            - '-c'
            - |
              # get ordinal number from hostname
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1;
              ordinal=${BASH_REMATCH[1]};
              printf 'server_id=%s\n' $ordinal >> /data/rtpengine/server_id.k;
              printf '#!trydef DBURL "%s"\n' $DBURL >> /data/rtpengine/db_url.k;
              printf '#!trydef RODBURL "%s"\n' $DBROURL >> /data/rtpengine/db_url.k;
              printf '#!trydef CONTACT_DB "contacts_db=>%s"\n' $DBROURL >> /data/rtpengine/db_url;
          volumeMounts:
            - name: rtpengine-config
              mountPath: /data/rtpengine
      containers:
      - name: kamailio
        # image: efficacy38/kamailio:v1.13
        image: efficacy38/kamailio:v1.16
        imagePullPolicy: Always
        # command: ["sleep", "infinity"]
        ports:
        - containerPort: 5060
        volumeMounts:
          - name: rtpengine-config
            mountPath: /data/rtpengine
          - name: kamailio-config
            mountPath: /etc/kamailio
