CREATE DATABASE $DATABASE CHARACTER SET $CHARSET;

# crate kamailio RW user
CREATE USER '${DBRWUSER}'@'$DBHOST' IDENTIFIED BY '$DBRWPW';
		GRANT ALL PRIVILEGES ON $1.* TO '${DBRWUSER}'@'$DBHOST';

# create kamailio RO user
CREATE USER '${DBROUSER}'@'$DBHOST' IDENTIFIED BY '$DBROPW';
			GRANT SELECT ON $1.* TO '${DBROUSER}'@'$DBHOST';
